### ISSUE TITLE
Error connecting to TTN indoor gateway...

### ISSUE THREAD

**Issue by jjanderson** [cyberjunky/home-assistant-ttn_gateway#1]
Logger: custom_components.ttn_gateway.sensor
Source: custom_components/ttn_gateway/sensor.py:123
Integration: ttn_gateway (documentation)
First occurred: 15:50:26 (4 occurrences)
Last logged: 15:51:08

Cannot connect to TTN Gateway: Cannot connect to host 192.168.1.93:80 ssl:default [Connect call failed ('192.168.1.93', 80)]

Gateway has been assigned static ip address at 192.168.1.93...

I appreciate that the information in this ticket may be scant, so please do let me know if you need any further information.

Thanks

**Comment by cyberjunky** [comment]
@jjanderson What do you get when you connect with a webbrowser to http://192.168.1.93/status.cgi ?

**Comment by jjanderson** [comment]
here: 
![image](https://user-images.githubusercontent.com/1214287/105222955-148b0380-5b53-11eb-8b9f-79f1404a956d.png)

THis is one of the new gateways not the original on kickstarter if that helps?

**Comment by cyberjunky** [comment]
@jjanderson Which kind of TTN Gateway model do you use? It's either not supported, or the IP address is different than you might think, remove cable an see if ping stop working.

**Comment by jjanderson** [comment]
it connects on wireless and I have assigned static IP address via UDM.... 

This si the gateway: https://www.thethingsnetwork.org/docs/gateways/thethingsindoor/

**Comment by cyberjunky** [comment]
@jjanderson I don't know if that one has a webserver and/or reports its status data and if so what the url is. The integration was build for the TTN Backer Edition
https://www.thethingsnetwork.org/docs/gateways/gateway/

If you can find out more info about your model I can try to adapt to it.

**Comment by jjanderson** [comment]
Hi, it’s not a major issue, however this one and the outdoor version are now the official TTN ones, I am not bothered really, but others may experience the same problem. I can help troubleshoot if you need. I mainly use chirpstack in any case so mot too bothered about ttn

**Comment by cyberjunky** [comment]
I will update the README with this information.
