### ISSUE TITLE
Port Host connection issue

### ISSUE THREAD

**Issue by alessandrosalafia** [cyberjunky/home-assistant-ttn_gateway#2]
Hi cyberjunky,
I am trying to integrate the dragino LPS8 gateway but the HACS component tries to connect to port 80 while the LPS8 connects to port 8000. From Dragino configuration it is not possible to change this port, at least I have not found it, also I would like to know if user and password are not required.

**Comment by cyberjunky** [comment]
@alessandrosalafia Hi, does the Dragino has the same rest api running?
Can you point me to the documentation?
