### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by gurrier** [cyberjunky/home-assistant-ttn_gateway#4]
I am trying to get the integration working but am seeing this in the HASS log...
The IP address is correct.

This error originated from a custom integration.

Logger: custom_components.ttn_gateway.sensor
Source: custom_components/ttn_gateway/sensor.py:123
Integration: ttn_gateway (documentation, issues)
First occurred: 10:04:00 AM (112 occurrences)
Last logged: 11:55:01 AM

Cannot connect to TTN Gateway:
Cannot connect to TTN Gateway: Cannot connect to host 192.168.86.32:80 ssl:default [Connect call failed ('192.168.86.32', 80)]

**Comment by gurrier** [comment]
I've just noticed that the TTN gateway you referred to in the doco is the outdoor version, not the indoor gateway which is what I have.  [TTIG
](https://www.thethingsindustries.com/docs/gateways/thethingsindoorgateway/)

Is that the problem?

**Comment by cyberjunky** [comment]
Yes correct, the indoor model doesn't have a local API as far as I know.
